name: Trigger Webhook

on:
  push:
    branches: [ '*' ]
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: ${{ github.event_name }}" \
            -d '{
              "ref": "${{ github.ref }}",
              "head_commit": {
                "id": "${{ github.sha }}"
              },
              "sender": {
                "login": "${{ github.actor }}"
              },
              "pull_request": {
                "number": ${{ github.event.pull_request.number || 'null' }},
                "head": {
                  "ref": "${{ github.head_ref || github.ref_name }}"
                },
                "base": {
                  "ref": "${{ github.base_ref || github.ref_name }}"
                },
                "merged": ${{ github.event.pull_request.merged || 'false' }}
              },
              "action": "${{ github.event.action }}"
            }' 